(()=>{
const KEY='reflash_ny_inventory_v1';
const seed=[
{id:'inv-001',address:'455 Bushwick Ave, Brooklyn, NY 11206',deal:'For Lease',type:'Retail',space:'1,800 SF',price:'Upon request',broker:'Listing contact via LoopNet',owner:'455 Bushwick LLC (possible current entity; verify ACRIS)',management:'Research needed',sourceUrl:'https://www.loopnet.com/Listing/455-Bushwick-Ave-Brooklyn-NY/38357627/',verified:'2026-07-16',ownerStatus:'research',status:'New lead',notes:'Corner retail; 93 ft wraparound frontage; 17 ft ceilings; availability stated as now. A similarly addressed LLC was formed in April 2026, but deed ownership must be verified.'},
{id:'inv-002',address:'455 Bushwick Ave, Brooklyn, NY 11206',deal:'For Sale',type:'Retail',space:'1,800 SF building',price:'Upon request',broker:'Listing contact via LoopNet',owner:'455 Bushwick LLC (possible current entity; verify ACRIS)',management:'Research needed',sourceUrl:'https://www.loopnet.com/Listing/455-Bushwick-Ave-Brooklyn-NY/38856439/',verified:'2026-07-16',ownerStatus:'research',status:'New lead',notes:'Vacant-delivery corner property marketed to investors or owner-users.'},
{id:'inv-003',address:'501 Bushwick Ave, Brooklyn, NY 11206',deal:'For Lease',type:'Retail',space:'391–6,952 SF; 13,620 SF total listed',price:'Upon request',broker:'KSR NY — Eli Yadid, Jordan Raphan, Akram Mozeb',owner:'Rabsky Group / affiliated ownership (verify current deed entity)',management:'Rabsky Group (reported developer/owner)',sourceUrl:'https://www.ksrny.com/listing/501-bushwick-avenue',verified:'2026-07-16',ownerStatus:'verified',status:'Researching',notes:'Multiple ground-floor spaces plus selling lower level. Immediate possession reported.'},
{id:'inv-004',address:'1224 Flushing Ave, Brooklyn, NY 11237',deal:'For Lease',type:'Retail',space:'Up to 10,000 SF',price:'$45–$65/SF/YR reported',broker:'Manu Wendum; Marisa Simkin; Corey Cohen',owner:'Flushing 1224 LLC',management:'David Moore / ownership representative reported',sourceUrl:'https://www.propertyshark.com/mason/Property/196166/1224-Flushing-Ave-Brooklyn-NY-11237/',verified:'2026-07-16',ownerStatus:'verified',status:'Researching',notes:'Whole Foods has reportedly signed for part of the property; confirm what space remains available.'},
{id:'inv-005',address:'1085 Willoughby Ave, Brooklyn, NY 11221',deal:'For Lease',type:'Retail',space:'3,600 SF',price:'$33/SF/YR',broker:'Contact property listing',owner:'Research needed',management:'Research needed',sourceUrl:'https://www.propertyshark.com/cre/retail/us/ny/brooklyn/bushwick/',verified:'2026-07-16',ownerStatus:'research',status:'New lead',notes:'Building reported as approximately 15,187 SF; current retail listing shown in Bushwick inventory.'},
{id:'inv-006',address:'412 Evergreen Ave, Brooklyn, NY 11221',deal:'For Lease',type:'Retail',space:'5,000 SF',price:'Contact for pricing',broker:'Contact property listing',owner:'Research needed',management:'Research needed',sourceUrl:'https://www.propertyshark.com/cre/retail/us/ny/brooklyn/bushwick/',verified:'2026-07-16',ownerStatus:'research',status:'New lead',notes:''},
{id:'inv-007',address:'792 Flushing Ave, Brooklyn, NY 11206',deal:'For Lease',type:'Retail',space:'1,300 SF',price:'Contact for pricing',broker:'Contact property listing',owner:'Research needed',management:'Research needed',sourceUrl:'https://www.propertyshark.com/cre/retail/us/ny/brooklyn/bushwick/',verified:'2026-07-16',ownerStatus:'research',status:'New lead',notes:''},
{id:'inv-008',address:'343 Himrod St, Brooklyn, NY 11237',deal:'For Lease',type:'Retail',space:'2,800 SF',price:'$54/SF/YR',broker:'Contact property listing',owner:'Research needed',management:'Research needed',sourceUrl:'https://www.propertyshark.com/cre/retail/us/ny/brooklyn/bushwick/',verified:'2026-07-16',ownerStatus:'research',status:'New lead',notes:''},
{id:'inv-009',address:'384 Knickerbocker Ave, Brooklyn, NY 11237',deal:'For Lease',type:'Retail',space:'3,000 SF',price:'Contact for pricing',broker:'Contact property listing',owner:'Research needed',management:'Research needed',sourceUrl:'https://www.propertyshark.com/cre/retail/us/ny/brooklyn/bushwick/',verified:'2026-07-16',ownerStatus:'research',status:'New lead',notes:''},
{id:'inv-010',address:'1317 Myrtle Ave, Brooklyn, NY 11221',deal:'For Lease',type:'Retail',space:'2,800 SF',price:'$37/SF/YR',broker:'Contact property listing',owner:'Research needed',management:'Research needed',sourceUrl:'https://www.propertyshark.com/cre/retail/us/ny/brooklyn/bushwick/',verified:'2026-07-16',ownerStatus:'research',status:'New lead',notes:''},
{id:'inv-011',address:'1255 Myrtle Ave, Brooklyn, NY 11221',deal:'For Lease',type:'Retail',space:'570 SF',price:'$59/SF/YR',broker:'Contact property listing',owner:'Research needed',management:'Research needed',sourceUrl:'https://www.propertyshark.com/cre/retail/us/ny/brooklyn/bushwick/',verified:'2026-07-16',ownerStatus:'research',status:'New lead',notes:''},
{id:'inv-012',address:'10 Troutman St, Brooklyn, NY 11206',deal:'For Lease',type:'Retail',space:'1,050 SF',price:'$40/SF/YR',broker:'Contact property listing',owner:'Research needed',management:'Research needed',sourceUrl:'https://www.propertyshark.com/cre/retail/us/ny/brooklyn/bushwick/',verified:'2026-07-16',ownerStatus:'research',status:'New lead',notes:''},
{id:'inv-013',address:'868 Wyckoff Ave, Brooklyn, NY 11237',deal:'For Lease',type:'Retail',space:'600 SF; 2 spaces reported',price:'$65/SF/YR',broker:'Contact property listing',owner:'Research needed',management:'Research needed',sourceUrl:'https://www.propertyshark.com/cre/retail/us/ny/brooklyn/bushwick/',verified:'2026-07-16',ownerStatus:'research',status:'New lead',notes:''},
{id:'inv-014',address:'300 Wyckoff Ave, Brooklyn, NY 11237',deal:'For Lease',type:'Retail',space:'32,000 SF',price:'Contact for pricing',broker:'Contact property listing',owner:'Research needed',management:'Research needed',sourceUrl:'https://www.propertyshark.com/cre/retail/us/ny/brooklyn/bushwick/',verified:'2026-07-16',ownerStatus:'research',status:'New lead',notes:''},
{id:'inv-015',address:'590 Bushwick Ave, Brooklyn, NY 11206',deal:'For Lease',type:'Retail',space:'1,000 SF',price:'Contact for pricing',broker:'Contact property listing',owner:'Research needed',management:'Research needed',sourceUrl:'https://www.propertyshark.com/cre/retail/us/ny/brooklyn/bushwick/',verified:'2026-07-16',ownerStatus:'research',status:'New lead',notes:''},
{id:'inv-016',address:'657 Knickerbocker Ave, Brooklyn, NY 11221',deal:'For Sale',type:'Multifamily',space:'8 units',price:'See current listing',broker:'Crexi listing contact',owner:'Research needed',management:'Research needed',sourceUrl:'https://www.crexi.com/properties/NY/Bushwick',verified:'2026-07-16',ownerStatus:'research',status:'New lead',notes:'Open-house indicator appeared in current Crexi search; verify active status and asking price.'},
{id:'inv-017',address:'1156 Myrtle Ave, Brooklyn, NY 11221',deal:'For Sale',type:'Multifamily',space:'Free-market multifamily building',price:'$3,190,000 reported',broker:'Crexi listing contact',owner:'Research needed',management:'Research needed',sourceUrl:'https://www.crexi.com/properties/NY/Bushwick',verified:'2026-07-16',ownerStatus:'research',status:'New lead',notes:''},
{id:'inv-018',address:'137 Wyckoff Ave, Brooklyn, NY 11237',deal:'For Sale',type:'Mixed Use',space:'Mixed-use investor property',price:'$4,700,000 reported',broker:'Crexi listing contact',owner:'Research needed',management:'Research needed',sourceUrl:'https://www.crexi.com/properties/NY/Bushwick',verified:'2026-07-16',ownerStatus:'research',status:'New lead',notes:'Listing mentions a national-franchise tenant.'},
{id:'inv-019',address:'102 Wyckoff Ave, Brooklyn, NY 11237',deal:'For Sale',type:'Land',space:'Development land',price:'$2,998,000 reported',broker:'Crexi listing contact',owner:'Research needed',management:'Research needed',sourceUrl:'https://www.crexi.com/properties/NY/Bushwick',verified:'2026-07-16',ownerStatus:'research',status:'New lead',notes:''},
{id:'inv-020',address:'103 Vanderveer St, Brooklyn, NY 11207',deal:'For Sale',type:'Land',space:'Approx. 5,500 buildable SF reported',price:'$950,000 reported',broker:'Crexi listing contact',owner:'Research needed',management:'Research needed',sourceUrl:'https://www.crexi.com/properties/NY/Bushwick',verified:'2026-07-16',ownerStatus:'research',status:'New lead',notes:''}
];
let items=JSON.parse(localStorage.getItem(KEY)||'null')||seed;
let selected=items[0]?.id||null;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function save(){localStorage.setItem(KEY,JSON.stringify(items));}
function filters(){return {q:(document.querySelector('#inventorySearch')?.value||'').toLowerCase(),deal:document.querySelector('#inventoryDealFilter')?.value||'all',type:document.querySelector('#inventoryTypeFilter')?.value||'all',owner:document.querySelector('#inventoryOwnerFilter')?.value||'all'};}
function visible(){const f=filters();return items.filter(x=>(f.deal==='all'||x.deal===f.deal)&&(f.type==='all'||x.type===f.type)&&(f.owner==='all'||(f.owner==='verified'?x.ownerStatus==='verified':x.ownerStatus!=='verified'))&&(!f.q||Object.values(x).join(' ').toLowerCase().includes(f.q)));}
function stats(){const lease=items.filter(x=>x.deal==='For Lease').length,sale=items.filter(x=>x.deal==='For Sale').length,owners=items.filter(x=>x.ownerStatus==='verified').length,research=items.length-owners;document.querySelector('#inventoryStats').innerHTML=`<div class="inventory-stat"><span>Total leads</span><strong>${items.length}</strong><small>Bushwick starter set</small></div><div class="inventory-stat"><span>For lease</span><strong>${lease}</strong><small>Active-source candidates</small></div><div class="inventory-stat"><span>For sale</span><strong>${sale}</strong><small>Investment/development</small></div><div class="inventory-stat"><span>Ownership queue</span><strong>${research}</strong><small>${owners} owner records started</small></div>`;}
function renderDetail(){const x=items.find(v=>v.id===selected);const el=document.querySelector('#inventoryDetail');if(!x){el.innerHTML='<div class="empty">Select a property.</div>';return;}el.innerHTML=`<p class="eyebrow">${esc(x.deal)} · ${esc(x.type)}</p><h2>${esc(x.address)}</h2><div><span class="inventory-pill ${x.ownerStatus==='verified'?'verified':'research'}">${x.ownerStatus==='verified'?'Owner identified':'Ownership verification needed'}</span><span class="inventory-pill">${esc(x.status||'New lead')}</span></div><dl><dt>Space</dt><dd>${esc(x.space)}</dd><dt>Price</dt><dd>${esc(x.price)}</dd><dt>Broker</dt><dd>${esc(x.broker)}</dd><dt>Owner/entity</dt><dd>${esc(x.owner)}</dd><dt>Management</dt><dd>${esc(x.management)}</dd><dt>Last checked</dt><dd>${esc(x.verified)}</dd></dl><div class="inventory-warning">Public listing and ownership information can change. Confirm through the listing broker, ACRIS, NYC Finance, HPD/DOB, and your brokerage before outreach or advertising.</div><h3>Research notes</h3><p class="inventory-note">${esc(x.notes||'No notes yet.')}</p><div class="inventory-detail-actions"><a class="primary" href="${esc(x.sourceUrl)}" target="_blank" rel="noopener">Open source</a><button data-inv-edit>Edit</button><button data-inv-map>Add to Mapper</button><button data-inv-task>Create follow-up</button><button class="danger" data-inv-delete>Delete</button></div><p class="inventory-source">Source: ${esc(x.sourceUrl)}</p>`;
el.querySelector('[data-inv-edit]').onclick=()=>openForm(x);el.querySelector('[data-inv-delete]').onclick=()=>{if(confirm('Delete this inventory record?')){items=items.filter(v=>v.id!==x.id);selected=items[0]?.id||null;save();renderInventory();}};el.querySelector('[data-inv-map]').onclick=()=>{const pins=JSON.parse(localStorage.getItem('reflash_mapper_state_v1')||'{}');pins.pins=pins.pins||[];pins.pins.push({id:Date.now(),title:x.address,address:x.address,type:x.deal==='For Sale'?'Residential Sale':'Lead',status:'active',notes:`${x.type} · ${x.space} · ${x.price}\nOwner: ${x.owner}`});localStorage.setItem('reflash_mapper_state_v1',JSON.stringify(pins));alert('Added to GPS Mapper. Geocode the address there if coordinates are blank.');};el.querySelector('[data-inv-task]').onclick=()=>{if(window.state){state.tasks.push({id:Date.now(),text:`Follow up: ${x.address}`,due:'',link:'',done:false});if(window.save)save();}alert('Follow-up added to Work agenda.');};}
function table(){const list=visible();document.querySelector('#inventoryCount').textContent=`${list.length} shown`;document.querySelector('#inventoryTable').innerHTML=list.length?`<table class="inventory-grid"><thead><tr><th>Property</th><th>Deal</th><th>Space</th><th>Asking</th><th>Owner</th><th>Status</th></tr></thead><tbody>${list.map(x=>`<tr data-inv-id="${x.id}" class="${x.id===selected?'active':''}"><td><div class="inventory-address">${esc(x.address)}</div><small>${esc(x.type)}</small></td><td>${esc(x.deal)}</td><td>${esc(x.space)}</td><td>${esc(x.price)}</td><td>${esc(x.owner)}</td><td><span class="inventory-pill ${x.ownerStatus==='verified'?'verified':'research'}">${x.ownerStatus==='verified'?'Started':'Research'}</span></td></tr>`).join('')}</tbody></table>`:'<div class="inventory-empty">No properties match these filters.</div>';document.querySelectorAll('[data-inv-id]').forEach(r=>r.onclick=()=>{selected=r.dataset.invId;table();renderDetail();});}
function openForm(x={}){const d=document.querySelector('#inventoryDialog'),f=document.querySelector('#inventoryForm');f.reset();Object.entries(x).forEach(([k,v])=>{if(f.elements[k])f.elements[k].value=v||'';});d.showModal();}
function csvCell(v){return `"${String(v??'').replace(/"/g,'""')}"`;}
function exportCSV(){const cols=['address','deal','type','space','price','broker','owner','management','status','verified','sourceUrl','notes'];const csv=[cols.join(','),...items.map(x=>cols.map(c=>csvCell(x[c])).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='REFLASH_NY_inventory.csv';a.click();URL.revokeObjectURL(a.href);}
function parseCSV(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++;}else if(c==='"')q=!q;else if(c===','&&!q){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}row.push(cell);if(row.some(Boolean))rows.push(row);const h=rows.shift()||[];return rows.map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]||''])));}
window.renderInventory=function(){stats();table();renderDetail();['inventorySearch','inventoryDealFilter','inventoryTypeFilter','inventoryOwnerFilter'].forEach(id=>{const el=document.querySelector('#'+id);if(el&&!el.dataset.bound){el.dataset.bound=1;el.addEventListener(id==='inventorySearch'?'input':'change',()=>{table();renderDetail();});}});document.querySelector('#inventoryAdd').onclick=()=>openForm();document.querySelector('#inventoryExport').onclick=exportCSV;document.querySelector('#inventoryImport').onchange=async e=>{const file=e.target.files[0];if(!file)return;const incoming=parseCSV(await file.text()).map((x,i)=>({...x,id:x.id||`import-${Date.now()}-${i}`,ownerStatus:x.owner&&x.owner!=='Research needed'?'verified':'research'}));items=[...incoming,...items];save();renderInventory();e.target.value='';};document.querySelector('#inventoryClose').onclick=()=>document.querySelector('#inventoryDialog').close();document.querySelector('#inventoryForm').onsubmit=e=>{e.preventDefault();const obj=Object.fromEntries(new FormData(e.target));obj.id=obj.id||`inv-${Date.now()}`;obj.verified=obj.verified||new Date().toISOString().slice(0,10);obj.ownerStatus=obj.owner&&obj.owner.trim()&&obj.owner!=='Research needed'?'verified':'research';obj.status=obj.status||'New lead';const i=items.findIndex(x=>x.id===obj.id);if(i>=0)items[i]={...items[i],...obj};else items.unshift(obj);selected=obj.id;save();document.querySelector('#inventoryDialog').close();renderInventory();};};
})();
